import { Match, League, Team, StatsItem, QuickAccessItem } from '@/types';

// ─── ESPN CDN helper ─────────────────────────────────────────────────────────
const espn = (id: number) => `https://a.espncdn.com/i/teamlogos/soccer/500/${id}.png`;
const flag = (code: string) => `https://flagcdn.com/h80/${code}.png`;

// ─── Club Leagues ────────────────────────────────────────────────────────────
export const LEAGUES: League[] = [
  {
    id: 'pl',
    name: 'Premier League',
    shortName: 'PL',
    logo: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    country: 'England',
    countryFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    matchesLive: 2,
    matchesToday: 6,
    color: '#3D195B',
    season: '2025/26',
    clubsCount: 20,
  },
  {
    id: 'ucl',
    name: 'UEFA Champions League',
    shortName: 'UCL',
    logo: '🏆',
    country: 'Europe',
    countryFlag: '🇪🇺',
    matchesLive: 4,
    matchesToday: 8,
    color: '#0B1560',
    season: '2025/26',
    clubsCount: 36,
  },
  {
    id: 'laliga',
    name: 'La Liga',
    shortName: 'LaLiga',
    logo: '🇪🇸',
    country: 'Spain',
    countryFlag: '🇪🇸',
    matchesLive: 1,
    matchesToday: 5,
    color: '#FF4500',
    season: '2025/26',
    clubsCount: 20,
  },
  {
    id: 'bundesliga',
    name: 'Bundesliga',
    shortName: 'BL',
    logo: '🦅',
    country: 'Germany',
    countryFlag: '🇩🇪',
    matchesLive: 0,
    matchesToday: 4,
    color: '#D30000',
    season: '2025/26',
    clubsCount: 18,
  },
  {
    id: 'serie_a',
    name: 'Serie A',
    shortName: 'SA',
    logo: '🇮🇹',
    country: 'Italy',
    countryFlag: '🇮🇹',
    matchesLive: 3,
    matchesToday: 7,
    color: '#009246',
    season: '2025/26',
    clubsCount: 20,
  },
  {
    id: 'ligue1',
    name: 'Ligue 1',
    shortName: 'L1',
    logo: '⚜️',
    country: 'France',
    countryFlag: '🇫🇷',
    matchesLive: 2,
    matchesToday: 5,
    color: '#003189',
    season: '2025/26',
    clubsCount: 18,
  },
  {
    id: 'wcq_afc',
    name: 'World Cup Qualifiers — AFC',
    shortName: 'WCQ AFC',
    logo: '🌏',
    country: 'Asia',
    countryFlag: '🌏',
    matchesLive: 2,
    matchesToday: 4,
    color: '#1565C0',
    season: '2026',
    clubsCount: 46,
  },
  {
    id: 'wcq_conmebol',
    name: 'World Cup Qualifiers — CONMEBOL',
    shortName: 'WCQ SAM',
    logo: '🌎',
    country: 'South America',
    countryFlag: '🌎',
    matchesLive: 1,
    matchesToday: 5,
    color: '#00695C',
    season: '2026',
    clubsCount: 10,
  },
  {
    id: 'wcq_uefa',
    name: 'World Cup Qualifiers — UEFA',
    shortName: 'WCQ EUR',
    logo: '🌍',
    country: 'Europe',
    countryFlag: '🇪🇺',
    matchesLive: 3,
    matchesToday: 10,
    color: '#4527A0',
    season: '2026',
    clubsCount: 54,
  },
  {
    id: 'nations_league',
    name: 'UEFA Nations League',
    shortName: 'UNL',
    logo: '🏅',
    country: 'Europe',
    countryFlag: '🇪🇺',
    matchesLive: 2,
    matchesToday: 8,
    color: '#006064',
    season: '2025/26',
    clubsCount: 54,
  },
  {
    id: 'copa_america',
    name: 'Copa América',
    shortName: 'Copa',
    logo: '🏆',
    country: 'South America',
    countryFlag: '🌎',
    matchesLive: 1,
    matchesToday: 3,
    color: '#B71C1C',
    season: '2024',
    clubsCount: 16,
  },
  {
    id: 'afcon',
    name: 'Africa Cup of Nations',
    shortName: 'AFCON',
    logo: '🌍',
    country: 'Africa',
    countryFlag: '🌍',
    matchesLive: 2,
    matchesToday: 4,
    color: '#1B5E20',
    season: '2025',
    clubsCount: 24,
  },
  {
    id: 'international_friendly',
    name: 'International Friendly',
    shortName: 'Friendly',
    logo: '🤝',
    country: 'International',
    countryFlag: '🌍',
    matchesLive: 1,
    matchesToday: 6,
    color: '#37474F',
    season: '2025',
    clubsCount: 0,
  },
];

// ─── Club Teams ──────────────────────────────────────────────────────────────
export const TEAMS: Record<string, Team> = {
  mancity:   { id: 'mancity',   name: 'Manchester City',    shortName: 'MCI', logo: '🔵', logoUrl: espn(382),  country: 'England', competition: 'Premier League',       followers: '45M' },
  arsenal:   { id: 'arsenal',   name: 'Arsenal',            shortName: 'ARS', logo: '🔴', logoUrl: espn(359),  country: 'England', competition: 'Premier League',       followers: '32M' },
  chelsea:   { id: 'chelsea',   name: 'Chelsea',            shortName: 'CHE', logo: '💙', logoUrl: espn(363),  country: 'England', competition: 'Premier League',       followers: '28M' },
  liverpool: { id: 'liverpool', name: 'Liverpool',          shortName: 'LIV', logo: '🔴', logoUrl: espn(364),  country: 'England', competition: 'Premier League',       followers: '40M' },
  manutd:    { id: 'manutd',    name: 'Manchester United',  shortName: 'MUN', logo: '🔴', logoUrl: espn(360),  country: 'England', competition: 'Premier League',       followers: '38M' },
  tottenham: { id: 'tottenham', name: 'Tottenham Hotspur',  shortName: 'TOT', logo: '⚪', logoUrl: espn(367),  country: 'England', competition: 'Premier League',       followers: '20M' },
  newcastle: { id: 'newcastle', name: 'Newcastle United',   shortName: 'NEW', logo: '⚫', logoUrl: espn(361),  country: 'England', competition: 'Premier League',       followers: '12M' },
  barca:     { id: 'barca',     name: 'Barcelona',          shortName: 'BAR', logo: '🔵', logoUrl: espn(83),   country: 'Spain',   competition: 'La Liga',              followers: '65M' },
  madrid:    { id: 'madrid',    name: 'Real Madrid',        shortName: 'RMA', logo: '⚪', logoUrl: espn(86),   country: 'Spain',   competition: 'La Liga',              followers: '75M' },
  atletico:  { id: 'atletico',  name: 'Atlético Madrid',   shortName: 'ATM', logo: '🔴', logoUrl: espn(1068), country: 'Spain',   competition: 'La Liga',              followers: '30M' },
  dortmund:  { id: 'dortmund',  name: 'Borussia Dortmund', shortName: 'BVB', logo: '🟡', logoUrl: espn(124),  country: 'Germany', competition: 'Bundesliga',           followers: '15M' },
  bayern:    { id: 'bayern',    name: 'Bayern Munich',      shortName: 'BAY', logo: '🔴', logoUrl: espn(132),  country: 'Germany', competition: 'Bundesliga',           followers: '35M' },
  psg:       { id: 'psg',       name: 'PSG',                shortName: 'PSG', logo: '🔵', logoUrl: espn(160),  country: 'France',  competition: 'Ligue 1',             followers: '38M' },
  juventus:  { id: 'juventus',  name: 'Juventus',           shortName: 'JUV', logo: '⚫', logoUrl: espn(111),  country: 'Italy',   competition: 'Serie A',             followers: '25M' },
  inter:     { id: 'inter',     name: 'Inter Milan',        shortName: 'INT', logo: '🔵', logoUrl: espn(110),  country: 'Italy',   competition: 'Serie A',             followers: '18M' },
  milan:     { id: 'milan',     name: 'AC Milan',           shortName: 'ACM', logo: '🔴', logoUrl: espn(103),  country: 'Italy',   competition: 'Serie A',             followers: '22M' },
  napoli:    { id: 'napoli',    name: 'Napoli',             shortName: 'NAP', logo: '🔵', logoUrl: espn(114),  country: 'Italy',   competition: 'Serie A',             followers: '15M' },
  ajax:      { id: 'ajax',      name: 'Ajax',               shortName: 'AJX', logo: '🔴', logoUrl: espn(235),  country: 'Netherlands', competition: 'Eredivisie',     followers: '10M' },
  porto:     { id: 'porto',     name: 'FC Porto',           shortName: 'POR', logo: '🔵', logoUrl: espn(662),  country: 'Portugal', competition: 'Primeira Liga',     followers: '8M'  },
  benfica:   { id: 'benfica',   name: 'Benfica',            shortName: 'BEN', logo: '🔴', logoUrl: espn(233),  country: 'Portugal', competition: 'Primeira Liga',     followers: '9M'  },
};

// ─── National Teams ───────────────────────────────────────────────────────────
export const NATIONAL_TEAMS: Record<string, Team> = {
  brazil:      { id: 'brazil',      name: 'Brazil',       shortName: 'BRA', logo: '🇧🇷', logoUrl: flag('br'),    country: 'Brazil',      isNational: true },
  argentina:   { id: 'argentina',   name: 'Argentina',    shortName: 'ARG', logo: '🇦🇷', logoUrl: flag('ar'),    country: 'Argentina',   isNational: true },
  france:      { id: 'france',      name: 'France',       shortName: 'FRA', logo: '🇫🇷', logoUrl: flag('fr'),    country: 'France',      isNational: true },
  england:     { id: 'england',     name: 'England',      shortName: 'ENG', logo: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', logoUrl: flag('gb-eng'), country: 'England',     isNational: true },
  germany:     { id: 'germany',     name: 'Germany',      shortName: 'GER', logo: '🇩🇪', logoUrl: flag('de'),    country: 'Germany',     isNational: true },
  spain:       { id: 'spain',       name: 'Spain',        shortName: 'ESP', logo: '🇪🇸', logoUrl: flag('es'),    country: 'Spain',       isNational: true },
  portugal:    { id: 'portugal',    name: 'Portugal',     shortName: 'POR', logo: '🇵🇹', logoUrl: flag('pt'),    country: 'Portugal',    isNational: true },
  italy:       { id: 'italy',       name: 'Italy',        shortName: 'ITA', logo: '🇮🇹', logoUrl: flag('it'),    country: 'Italy',       isNational: true },
  netherlands: { id: 'netherlands', name: 'Netherlands',  shortName: 'NED', logo: '🇳🇱', logoUrl: flag('nl'),    country: 'Netherlands', isNational: true },
  belgium:     { id: 'belgium',     name: 'Belgium',      shortName: 'BEL', logo: '🇧🇪', logoUrl: flag('be'),    country: 'Belgium',     isNational: true },
  croatia:     { id: 'croatia',     name: 'Croatia',      shortName: 'CRO', logo: '🇭🇷', logoUrl: flag('hr'),    country: 'Croatia',     isNational: true },
  uruguay:     { id: 'uruguay',     name: 'Uruguay',      shortName: 'URU', logo: '🇺🇾', logoUrl: flag('uy'),    country: 'Uruguay',     isNational: true },
  colombia:    { id: 'colombia',    name: 'Colombia',     shortName: 'COL', logo: '🇨🇴', logoUrl: flag('co'),    country: 'Colombia',    isNational: true },
  morocco:     { id: 'morocco',     name: 'Morocco',      shortName: 'MAR', logo: '🇲🇦', logoUrl: flag('ma'),    country: 'Morocco',     isNational: true },
  japan:       { id: 'japan',       name: 'Japan',        shortName: 'JPN', logo: '🇯🇵', logoUrl: flag('jp'),    country: 'Japan',       isNational: true },
  senegal:     { id: 'senegal',     name: 'Senegal',      shortName: 'SEN', logo: '🇸🇳', logoUrl: flag('sn'),    country: 'Senegal',     isNational: true },
  nigeria:     { id: 'nigeria',     name: 'Nigeria',      shortName: 'NGA', logo: '🇳🇬', logoUrl: flag('ng'),    country: 'Nigeria',     isNational: true },
  usa:         { id: 'usa',         name: 'USA',          shortName: 'USA', logo: '🇺🇸', logoUrl: flag('us'),    country: 'USA',         isNational: true },
  mexico:      { id: 'mexico',      name: 'Mexico',       shortName: 'MEX', logo: '🇲🇽', logoUrl: flag('mx'),    country: 'Mexico',      isNational: true },
  southkorea:  { id: 'southkorea',  name: 'South Korea',  shortName: 'KOR', logo: '🇰🇷', logoUrl: flag('kr'),    country: 'South Korea', isNational: true },
  australia:   { id: 'australia',   name: 'Australia',    shortName: 'AUS', logo: '🇦🇺', logoUrl: flag('au'),    country: 'Australia',   isNational: true },
};

// Famous clubs for showcase
export const FAMOUS_CLUBS: Team[] = [
  TEAMS.madrid, TEAMS.barca, TEAMS.mancity, TEAMS.bayern, TEAMS.liverpool, TEAMS.juventus,
  TEAMS.arsenal, TEAMS.psg, TEAMS.inter, TEAMS.dortmund, TEAMS.atletico, TEAMS.milan,
];

// ─── Live Club Matches ────────────────────────────────────────────────────────
export const LIVE_MATCHES: Match[] = [
  {
    id: 'lm1',
    homeTeam: TEAMS.arsenal,
    awayTeam: TEAMS.mancity,
    homeScore: 2,
    awayScore: 1,
    status: 'live',
    minute: 67,
    startTime: new Date(Date.now() - 67 * 60 * 1000).toISOString(),
    league: LEAGUES[0],
    venue: 'Emirates Stadium, London',
    stats: {
      possession: [54, 46],
      shots: [14, 9],
      shotsOnTarget: [6, 4],
      corners: [7, 3],
      fouls: [10, 12],
      yellowCards: [2, 1],
      redCards: [0, 0],
    },
    events: [
      { id: 'e1', type: 'goal',        minute: 23, team: 'home', playerName: 'Saka',       assistName: 'Ødegaard' },
      { id: 'e2', type: 'yellow_card', minute: 34, team: 'away', playerName: 'Rodri' },
      { id: 'e3', type: 'goal',        minute: 51, team: 'away', playerName: 'Haaland' },
      { id: 'e4', type: 'goal',        minute: 58, team: 'home', playerName: 'Martinelli', assistName: 'Trossard' },
    ],
  },
  {
    id: 'lm2',
    homeTeam: TEAMS.barca,
    awayTeam: TEAMS.madrid,
    homeScore: 1,
    awayScore: 1,
    status: 'live',
    minute: 82,
    startTime: new Date(Date.now() - 82 * 60 * 1000).toISOString(),
    league: LEAGUES[2],
    venue: 'Spotify Camp Nou, Barcelona',
    stats: {
      possession: [58, 42],
      shots: [16, 11],
      shotsOnTarget: [5, 6],
      corners: [9, 4],
      fouls: [8, 14],
      yellowCards: [3, 2],
      redCards: [0, 0],
    },
    events: [
      { id: 'e5', type: 'goal',        minute: 12, team: 'away', playerName: 'Vinícius Jr.' },
      { id: 'e6', type: 'goal',        minute: 45, team: 'home', playerName: 'Lewandowski' },
      { id: 'e7', type: 'yellow_card', minute: 67, team: 'home', playerName: 'Gavi' },
    ],
  },
  {
    id: 'lm3',
    homeTeam: TEAMS.inter,
    awayTeam: TEAMS.milan,
    homeScore: 0,
    awayScore: 0,
    status: 'live',
    minute: 31,
    startTime: new Date(Date.now() - 31 * 60 * 1000).toISOString(),
    league: LEAGUES[4],
    venue: 'San Siro, Milan',
    stats: {
      possession: [48, 52],
      shots: [5, 7],
      shotsOnTarget: [2, 3],
      corners: [3, 5],
      fouls: [7, 9],
      yellowCards: [1, 2],
      redCards: [0, 0],
    },
    events: [
      { id: 'e8', type: 'yellow_card', minute: 18, team: 'away', playerName: 'Theo Hernández' },
    ],
  },
  // ── Live International Matches ──────────────────────────────────────────────
  {
    id: 'lm4',
    homeTeam: NATIONAL_TEAMS.brazil,
    awayTeam: NATIONAL_TEAMS.argentina,
    homeScore: 1,
    awayScore: 0,
    status: 'live',
    minute: 55,
    startTime: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    league: LEAGUES[7], // CONMEBOL WCQ
    venue: 'Maracanã, Rio de Janeiro',
    stats: {
      possession: [52, 48],
      shots: [11, 8],
      shotsOnTarget: [4, 3],
      corners: [6, 4],
      fouls: [9, 11],
      yellowCards: [1, 2],
      redCards: [0, 0],
    },
    events: [
      { id: 'ei1', type: 'goal',        minute: 38, team: 'home', playerName: 'Vinicius Jr.', assistName: 'Rodrygo' },
      { id: 'ei2', type: 'yellow_card', minute: 44, team: 'away', playerName: 'De Paul' },
    ],
  },
  {
    id: 'lm5',
    homeTeam: NATIONAL_TEAMS.england,
    awayTeam: NATIONAL_TEAMS.france,
    homeScore: 2,
    awayScore: 2,
    status: 'live',
    minute: 88,
    startTime: new Date(Date.now() - 88 * 60 * 1000).toISOString(),
    league: LEAGUES[9], // Nations League
    venue: 'Wembley Stadium, London',
    stats: {
      possession: [46, 54],
      shots: [12, 15],
      shotsOnTarget: [6, 7],
      corners: [5, 8],
      fouls: [11, 9],
      yellowCards: [2, 3],
      redCards: [0, 0],
    },
    events: [
      { id: 'ei3', type: 'goal',        minute: 14, team: 'home', playerName: 'Bellingham',   assistName: 'Saka' },
      { id: 'ei4', type: 'goal',        minute: 29, team: 'away', playerName: 'Mbappé' },
      { id: 'ei5', type: 'goal',        minute: 61, team: 'home', playerName: 'Kane',          assistName: 'Bellingham' },
      { id: 'ei6', type: 'goal',        minute: 79, team: 'away', playerName: 'Griezmann',     assistName: 'Mbappé' },
    ],
  },
  {
    id: 'lm6',
    homeTeam: NATIONAL_TEAMS.japan,
    awayTeam: NATIONAL_TEAMS.southkorea,
    homeScore: 1,
    awayScore: 1,
    status: 'live',
    minute: 72,
    startTime: new Date(Date.now() - 72 * 60 * 1000).toISOString(),
    league: LEAGUES[6], // AFC WCQ
    venue: 'Japan National Stadium, Tokyo',
    stats: {
      possession: [53, 47],
      shots: [9, 10],
      shotsOnTarget: [4, 5],
      corners: [4, 6],
      fouls: [12, 8],
      yellowCards: [1, 1],
      redCards: [0, 0],
    },
    events: [
      { id: 'ei7', type: 'goal', minute: 22, team: 'home', playerName: 'Mitoma' },
      { id: 'ei8', type: 'goal', minute: 55, team: 'away', playerName: 'Son Heung-min' },
    ],
  },
];

// ─── Upcoming Matches (Clubs + Nationals) ─────────────────────────────────────
export const UPCOMING_MATCHES: Match[] = [
  {
    id: 'um1',
    homeTeam: TEAMS.chelsea,
    awayTeam: TEAMS.liverpool,
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    league: LEAGUES[0],
    venue: 'Stamford Bridge, London',
  },
  {
    id: 'um2',
    homeTeam: TEAMS.bayern,
    awayTeam: TEAMS.juventus,
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
    startTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    league: LEAGUES[1],
    venue: 'Allianz Arena, Munich',
  },
  {
    id: 'um3',
    homeTeam: TEAMS.madrid,
    awayTeam: TEAMS.psg,
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
    startTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    league: LEAGUES[1],
    venue: 'Santiago Bernabéu, Madrid',
  },
  {
    id: 'um4',
    homeTeam: TEAMS.dortmund,
    awayTeam: TEAMS.atletico,
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
    startTime: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    league: LEAGUES[1],
    venue: 'Signal Iduna Park, Dortmund',
  },
  {
    id: 'um5',
    homeTeam: TEAMS.napoli,
    awayTeam: TEAMS.inter,
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
    startTime: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    league: LEAGUES[4],
    venue: 'Stadio Diego Armando Maradona, Naples',
  },
  // ── Upcoming International ─────────────────────────────────────────────────
  {
    id: 'um6',
    homeTeam: NATIONAL_TEAMS.germany,
    awayTeam: NATIONAL_TEAMS.spain,
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
    startTime: new Date(Date.now() + 1.5 * 60 * 60 * 1000).toISOString(),
    league: LEAGUES[8], // UEFA WCQ
    venue: 'Allianz Arena, Munich',
  },
  {
    id: 'um7',
    homeTeam: NATIONAL_TEAMS.portugal,
    awayTeam: NATIONAL_TEAMS.netherlands,
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
    startTime: new Date(Date.now() + 3.5 * 60 * 60 * 1000).toISOString(),
    league: LEAGUES[9], // Nations League
    venue: 'Estádio da Luz, Lisbon',
  },
  {
    id: 'um8',
    homeTeam: NATIONAL_TEAMS.morocco,
    awayTeam: NATIONAL_TEAMS.senegal,
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
    startTime: new Date(Date.now() + 7 * 60 * 60 * 1000).toISOString(),
    league: LEAGUES[11], // AFCON
    venue: 'Stade Mohammed V, Casablanca',
  },
  {
    id: 'um9',
    homeTeam: NATIONAL_TEAMS.colombia,
    awayTeam: NATIONAL_TEAMS.uruguay,
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
    startTime: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    league: LEAGUES[7], // CONMEBOL WCQ
    venue: 'Estadio Metropolitano, Barranquilla',
  },
  {
    id: 'um10',
    homeTeam: NATIONAL_TEAMS.usa,
    awayTeam: NATIONAL_TEAMS.mexico,
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
    startTime: new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString(),
    league: LEAGUES[12], // International Friendly
    venue: 'Rose Bowl, Los Angeles',
  },
  {
    id: 'um11',
    homeTeam: NATIONAL_TEAMS.italy,
    awayTeam: NATIONAL_TEAMS.belgium,
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
    startTime: new Date(Date.now() + 2.5 * 60 * 60 * 1000).toISOString(),
    league: LEAGUES[8], // UEFA WCQ
    venue: 'Stadio Olimpico, Rome',
  },
  {
    id: 'um12',
    homeTeam: NATIONAL_TEAMS.australia,
    awayTeam: NATIONAL_TEAMS.japan,
    homeScore: null,
    awayScore: null,
    status: 'upcoming',
    startTime: new Date(Date.now() + 10 * 60 * 60 * 1000).toISOString(),
    league: LEAGUES[6], // AFC WCQ
    venue: 'Stadium Australia, Sydney',
  },
];

// ─── Platform Stats ───────────────────────────────────────────────────────────
export const PLATFORM_STATS: StatsItem[] = [
  { label: 'Live Matches', value: LIVE_MATCHES.length, icon: 'Radio', color: '#00E676' },
  { label: 'Matches Today', value: LIVE_MATCHES.length + UPCOMING_MATCHES.length, icon: 'Calendar' },
  { label: 'Competitions', value: '120+', icon: 'Trophy' },
  { label: 'Registered Users', value: '2.4M', icon: 'Users' },
];

export const FEATURED_MATCH = LIVE_MATCHES[0];

export const QUICK_ACCESS_ITEMS: QuickAccessItem[] = [
  { id: 'qa1', title: 'Live Matches',    description: 'Track ongoing fixtures with live stats, updates & action commentary.', icon: 'Radio',    href: '/live' },
  { id: 'qa2', title: 'Watch Live TV',   description: 'Stream live football channels from Sky Sports, ESPN, beIN Sports.', icon: 'Tv',       href: '/watch' },
  { id: 'qa3', title: 'Match Schedule',  description: 'Check kick-off timetables for clubs & national teams this week.', icon: 'Calendar', href: '/schedule' },
  { id: 'qa4', title: 'Competitions',    description: 'Clubs, Nations League, World Cup Qualifiers & more.', icon: 'Trophy',   href: '/leagues' },
];

export const POPULAR_SEARCHES = [
  'Brazil vs Argentina', 'Premier League', 'Real Madrid', 'England vs France',
  'Champions League', 'World Cup Qualifiers', 'Barcelona',
];

export const RECENT_SEARCHES = ['El Clásico', 'Japan vs Korea', 'Nations League'];
